### ISSUE TITLE
Settings window appears at startup when "Start at Login" option enabled on Sequoia

### ISSUE THREAD

**Issue by tosbaha** [amebalabs/TRex#36] opened 2024-08-14 12:04 UTC
Previously, the application would start in the background when the "Start at Login" option was enabled. However, after the Sequoia update, enabling this option causes the settings window to always appear automatically when the computer starts.

**Comment by melonamin** [comment] 2024-08-17 14:09
Thanks for reporting. I see this as well. I will look into it when I confirm that this is not a bug in the BETA OS.

**Comment by ecthelionvi** [comment] 2024-09-17 02:55
+1 on this bug. I also cannot seem to close the settings menu without closing the app all together.

**Comment by melonamin** [comment] 2024-09-17 09:22
>  I also cannot seem to close the settings menu without closing the app all together.

Now, that's is weird. Can you confirm?

**Comment by det-box** [comment] 2024-09-18 17:56
+1, when starting (autostart at login or Manuel) the settings window opens every time

**Comment by wjfeeney** [comment] 2024-09-18 19:23
+1, I have the same issue

**Comment by det-box** [comment] 2024-09-30 13:31
Hello,
No news about this bug?

**Comment by qns7** [comment] 2024-10-11 22:20
+1

**Comment by Redstra** [comment] 2024-10-17 09:33
@melonamin  This issue has been open for quite a while now, and I wanted to check if there are any updates on a fix. It’s a key blocker for some of us, so I’d appreciate if it could be considered a higher priority.

**Comment by melonamin** [comment] 2024-10-17 09:59
@Redstra This is a pain in the back to test/debug, and I just didn't have enough time yet. Something has changed in the OS behavior.

> It’s a key blocker for some of us

Do you mind explaining why it is such a big issue for you? I understand that it is annoying, but honestly, I didn't consider it in any way critical.

**Comment by Redstra** [comment] 2024-10-17 23:21
@melonamin Thanks for your reply. I understand that debugging this must be difficult. For me, the issue with the settings window opening on every restart is disruptive because it interferes with my workflow and makes the app feel less polished, together with the bug that when I choose to hide the menu icon, there’s no way to access the settings again, which makes it tricky to adjust anything afterward.

I know it’s a free tool, and I really appreciate all the work you’ve put into it so far. It’s been one of my most used apps, and that’s why I wanted to share why it’s a bigger issue for me. Thanks again!

**Comment by melonamin** [comment] 2024-10-17 23:26
Ok, fair enough, I'll spend more time on it this weekend.

Thank you for keeping me to a higher standard.

**Comment by melonamin** [comment] 2024-10-20 18:44
Please try if [1.7.1 BETA 1](https://github.com/amebalabs/TRex/releases/tag/v1.7.1-BETA-1) works, it seems to behave well on my end.

**Comment by Redstra** [comment] 2024-10-22 15:20
@melonamin It works great, thanks for your effort and for taking our feedback into account! One more thing: when “Hide Menu Bar icon” is selected, there’s no way to access the settings window. Could you fix that as well?

Thanks again!

**Comment by melonamin** [comment] 2024-10-22 15:23
@Redstra in this version, when menu bar is hidden, try launching TRex again, this should open the settings.

**Comment by Redstra** [comment] 2024-10-22 15:41
@melonamin https://www.loom.com/share/9b366df463684a169181a21b3ba6fe74?sid=43739523-dadd-4396-8b1e-e9f44d6235fd
Here’s a screen recording showing the behavior when I try to ‘relaunch’ the app after hiding the icon. The only way to access the settings window is by force-closing the app through Activity Monitor, then deleting it with AppCleaner, reinstalling, and reopening it.

**Comment by melonamin** [comment] 2024-10-22 16:36
Well, that sucks, cause it totally works on my machine(s) 😐

Will look into it.

**Comment by melonamin** [comment] 2024-10-31 18:27
Gave it another go, please [take a look](https://github.com/amebalabs/TRex/releases/tag/v1.8.0-BETA-1)

**Comment by Redstra** [comment] 2024-10-31 19:29
@melonamin Works perfectly now! Thanks for your effort, no issues with the app now

**Comment by det-box** [comment] 2024-11-01 11:48
@melonamin Works now perfekt. Thanks

**Closed as completed** 2024-11-04 13:42 UTC
Labels: bug

**Comment by ElhemEnohpi** [comment] 2025-06-17 01:56
I'm seeing the "Welcome to TRex" and preferences window every time I restart. Using 1.8.1 on macOS 15.5. Was there a regression on this?
